name: rest_api
description: Dart package which represent an abstract layer for rest api services.
publish_to: none

environment:
  sdk: ">=2.17.0 <3.0.0"
  
dependencies: {dio: ^4.0.6, flutter_secure_storage: ^6.0.0}
